spring:
  application:
    name: business-common
  profiles:
    active: dev
server:
  servlet:
    context-path: /business-common
  port: 8210

my:
  spring:
    redis:
      pool:
        minIdle: 0
        maxIdle: 10
        maxActive: 10

---
spring:
  profiles: dev_desk
my:
  spring:
    redis:
      cluster:
        nodes: ['192.168.1.115:6380']

---
spring:
  profiles: ut
my:
  spring:
    redis:
      port: ${random.int(10000,50000)}
